### ISSUE TITLE
Please check your bot token

### ISSUE THREAD

**Issue by Mafhoom** [snow922841/telegram_channel_downloader#13]
Please check your bot token

I have not bot token, I have only phonenumber /api_id/api_hash
I want download all pdf files of a special public channel,
would you please add an example command here?
thx

**Comment by Mafhoom** [comment]
I want do this in win10 how must I put the path for my files?
Is there any counter shows the progress?

**Comment by snow922841** [comment]
> Please check your bot token
> 
> 
> 
> I have not bot token, I have only phonenumber /api_id/api_hash
> 
> I want download all pdf files of a special public channel,
> 
> would you please add an example command here?
> 
> thx

https://docs.telethon.dev/en/stable/concepts/botapi-vs-mtproto.html#what-is-bot-api

**Comment by snow922841** [comment]
> I want do this in win10 how must I put the path for my files?
> 
> Is there any counter shows the progress?

path like "c:\\user\\downloads"

Sorry there is currently no counter
