### ISSUE TITLE
出现异常，重新尝试下载！- Error

### ISSUE THREAD

**Issue by roshanconnor123** [snow922841/telegram_channel_downloader#14]
Hi there
First of all Thank you very much for this tool
It works wonderfully
I am having this error since some days
This error keeps popping up when I am trying to download a channel containing more than 500 Files

`出现异常，重新尝试下载！`

Is there any way to resolve this..

Thank you

**Comment by snow922841** [comment]
> Hi there
> 
> First of all Thank you very much for this tool
> 
> It works wonderfully
> 
> I am having this error since some days
> 
> This error keeps popping up when I am trying to download a channel containing more than 500 Files
> 
> 
> 
> `出现异常，重新尝试下载！`
> 
> 
> 
> Is there any way to resolve this..
> 
> 
> 
> Thank you

When we request a file to be downloaded from the telegram server, some parameters will be returned. One of the key parameters ref is only valid for two hours, so if your channel cannot be downloaded within two hours, an error will inevitably occur.  But I have added an exception retry, so you don’t need to worry.

**Comment by roshanconnor123** [comment]
Thank you for replying


> But I have added an exception retry, so you don’t need to worry.

I didnt get this though
I mean its just retrying..but its not downloading succesfully

**Comment by snow922841** [comment]
you can tell me channel url, i can try download its

**Comment by roshanconnor123** [comment]
Sure..Thank you

Here is the channel Link : https://t.me/koreanmovieshub

> you can tell me channel url, i can try download its

**Comment by snow922841** [comment]
i think you need update to latest version

**Comment by roshanconnor123** [comment]
> i think you need update to latest version

Oh..I had forked your repo here and made a english version
Actually I was using it all this time 
https://github.com/roshanconnor123/telegram_channel_downloader
I had forked it 13 days before..so I think its the latest
Maybe I made some errors while editing

**Comment by snow922841** [comment]
I want to ask you about the approximate speed when downloading files, for example, how long does it take for a 1G file

**Comment by roshanconnor123** [comment]
Its taking around 4 minutes approximately

I kept parallel downloads 10 at a time

**Comment by snow922841** [comment]
can you tell me your telegram username

**Comment by roshanconnor123** [comment]
> can you tell me your telegram username

@Roshanconnor

This is my Telegram Username
Thank you
