### ISSUE TITLE
部分频道无法进行下载

### ISSUE THREAD

**Issue by 1634222787** [snow922841/telegram_channel_downloader#16]
部分频道的，媒体文件无法下载，具体表现是这样的
蓝苍星:
/start https://t.me/fkdhlg 0
开始从疯狂的火龙果的第0条消息下载。
疯狂的火龙果 all message added to task queue, last message is：2528
bot信息显示正常，但是控制台没有相关输出
以下为控制台输出
2020-10-13 12:00:43 - 开始下载：疯狂的火龙果(1319561882) - 0
本地没有相关文件生成，配置自动上传的谷歌网盘中也没有相应文件或者文件夹
@Tasikaio这是我的TG账号issue交流实在不便╯▂╰

**Comment by snow922841** [comment]
已经联系你的电报

**Comment by nanbobike** [comment]
怎么解决 能分享我吗
