### ISSUE TITLE
报错 ModuleNotFoundError: No module named 'true'

### ISSUE THREAD

**Issue by hwmbing11** [snow922841/telegram_channel_downloader#18]
好像是个模块吧 这个报错研究了好久 实在是没找到什么原因 可能是我基础不好吧

**Comment by snow922841** [comment]
> 好像是个模块吧 这个报错研究了好久 实在是没找到什么原因 可能是我基础不好吧  

true是关键字，应该是你哪个地方的空格弄错了，你把完整的报错信息发给我
