### ISSUE TITLE
Perfectly downloading.....and then suddenly stops working.

### ISSUE THREAD

**Issue by microtechton** [snow922841/telegram_channel_downloader#19]
Hey there, sorry to speak in English if it is not your known language. I was using your script, except translated some chinese text to English. First 670 messages in a channel worked perfectly.... However, afterwards.... the scripts spitting only exceptions, is this a bug in your code? Or a Telegram API restriction?

![image](https://user-images.githubusercontent.com/48565151/98066964-74acbc00-1e26-11eb-929f-07077f56ad99.png)

**Comment by snow922841** [comment]
> Hey there, sorry to speak in English if it is not your known language. I was using your script, except translated some chinese text to English. First 670 messages in a channel worked perfectly.... However, afterwards.... the scripts spitting only exceptions, is this a bug in your code? Or a Telegram API restriction?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/48565151/98066964-74acbc00-1e26-11eb-929f-07077f56ad99.png)
> 
> Downloading files from telegram requires a parameter: ref, but this parameter has a validity period of two hours. If the download is not completed for two hours, an exception will occur.  But my script has added an exception retry, so you only need to check if there is a download in your download folder.

**Comment by snow922841** [comment]
> Hey there, sorry to speak in English if it is not your known language. I was using your script, except translated some chinese text to English. First 670 messages in a channel worked perfectly.... However, afterwards.... the scripts spitting only exceptions, is this a bug in your code? Or a Telegram API restriction?
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/48565151/98066964-74acbc00-1e26-11eb-929f-07077f56ad99.png)
> 
> 

Downloading files from telegram requires a parameter: ref, but this parameter has a validity period of two hours. If the download is not completed for two hours, an exception will occur.  But my script has added an exception retry, so you only need to check if there is a download in your download folder.
