### ISSUE TITLE
General Question

### ISSUE THREAD

**Issue by mesol86** [snow922841/telegram_channel_downloader#20]
Hi, I love your script since it can be automatically uploaded to Google Drive.

Just curious on how safe is this script? Is there any cases where Telegram banned the telephone number used by this script?

And I saw you just update the script today, may we know what is the changes?

**Comment by snow922841** [comment]
> Hi, I love your script since it can be automatically uploaded to Google Drive.
> 
> thanks 
> 
> Just curious on how safe is this script? Is there any cases where Telegram banned the telephone number used by this script?
> 
> 抱歉，我不太理解你的意思，为什么会禁止使用电话号码？
> 
> And I saw you just update the script today, may we know what is the changes?

这次更新修复了一个错误，在消息类型为网页或者主题时会出现异常

**Comment by mesol86** [comment]
> > 抱歉，我不太理解你的意思，为什么会禁止使用电话号码？

There are telegram bots/python script that use too much resources or hitting Telegram APIs aggressively. For example, script that can scrape users from Telegram Group and batch add the scraped users to new Group. This continuously hit the APIs and Telegram will ban the phone number that uses the API. So, I'm worried that this script will do the same.

**Comment by snow922841** [comment]
> 
> 
> > > 抱歉，我不太理解你的意思，为什么会禁止使用电话号码？
> 
> 
> 
> There are telegram bots/python script that use too much resources or hitting Telegram APIs aggressively. For example, script that can scrape users from Telegram Group and batch add the scraped users to new Group. This continuously hit the APIs and Telegram will ban the phone number that uses the API. So, I'm worried that this script will do the same.
> 
> 
> 
> 

请放心，这个脚本只会下载文件，并在出现一些异常情况的时候给你的电报发送通知，不会给其他任何人发送通知，所以你不必担心会被封禁

**Comment by mesol86** [comment]
> 
> 请放心，这个脚本只会下载文件，并在出现一些异常情况的时候给你的电报发送通知，不会给其他任何人发送通知，所以你不必担心会被封禁

Thank you very much for the assurance.
