### ISSUE TITLE
某个位置不管怎么修改都是报错

### ISSUE THREAD

**Issue by southcat** [snow922841/telegram_channel_downloader#21]
root@localhost:~/telegram_channel_downloader# python3 tg_channel_downloader.py
  File "tg_channel_downloader.py", line 87
    dirname = validateTitle(f'{chat_title}{entity.id}')
                                                                           ^
SyntaxError: invalid syntax
 
python3.5不知道为什么会一直报错这个位置  我自己修改过之后这个位置也是报错

**Comment by snow922841** [comment]
3.5倒是没有测试过，你可以尝试在其他设备运行看是否会报错。挺多人用这个脚本，但是你这个问题就只有你一个。

**Comment by southcat** [comment]
您用的什么版本我现在3.6有其他位置的报错3.6往下的版本没有f‘’这个格式化方法所以会报错

**Comment by snow922841** [comment]
> 您用的什么版本我现在3.6有其他位置的报错3.6往下的版本没有f‘’这个格式化方法所以会报错

原来如此，那最低要求就是3.6了，用3.6会报什么错，我帮你看一下

**Comment by southcat** [comment]
晚上给您发 174行可能是编码有问题运行有报错

**Comment by southcat** [comment]
164行 开始下载那里

**Comment by snow922841** [comment]
> 164行 开始下载那里

应该是报私人对话没有title这个属性吧，这个没有影响。

**Comment by southcat** [comment]
root@localhost:~/telegram_channel_downloader# python3 tg_channel_downloader.py
Successfully started (Press Ctrl+C to stop)
2020-11-17 07:03:05,549 - telethon.client.updates - ERROR - Unhandled exception on handler
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/telethon/client/updates.py", line 446, in _dispatch_update
    await callback(event)
  File "tg_channel_downloader.py", line 165, in handler
    print(f'{get_local_time()} - start download:{chat_title}({entity.id}) - {offset_id}')
UnicodeEncodeError: 'latin-1' codec can't encode characters in position 37-42: ordinal not in range(256)


报错之后机器人也没有返回 注释掉就行了 但是文件没有正常被下载下来

**Comment by snow922841** [comment]
你这个问题是第一次看到。大概群组名有什么问题。你换个系统试试把。

**Comment by southcat** [comment]
您那边用的什么系统和python版本  我换一下系统和版本再试试

**Comment by snow922841** [comment]
测试环境 Ubuntu 18.04.5 LTS & Python 3.6.9

**Comment by southcat** [comment]
好的我换系统试一下

**Comment by snow922841** [comment]
你电报多少，电报联系方便一点

**Comment by southcat** [comment]
http://t.me/southcat
