### ISSUE TITLE
下载没速度

### ISSUE THREAD

**Issue by creazytom** [snow922841/telegram_channel_downloader#22]
添加了两三个频道下载，刚开始下载速度二三M/S,但是只下载了第一个频道的第一个月，然后就一直不动了，在小鸡监控上，只有10k的速度了,bot机器人只是回了两条xx频道all message added to task queue, last message is：4313，在小鸡上报错2020-12-16 21:32:19,685 - telethon.client.users - WARNING - Telegram is having internal issues PersistentTimestampOutdatedError: Persistent timestamp outdated (caused by GetChannelDifferenceRequest)

**Comment by snow922841** [comment]
建议更换VPS所在网址，亚洲的数据中心在新加坡，所以在新加坡的VPS下载可能会快一点。
