### ISSUE TITLE
开启监控，不自动下载上传文件

### ISSUE THREAD

**Issue by Aceeea** [snow922841/telegram_channel_downloader#23]
开启监控消息，起初1-2天内会自动下载，之后就不会，需要重新启动软件才能自动下载上传。

**Comment by evrstr** [comment]
我的也是

**Comment by 520xcy** [comment]
me too

**Comment by snow922841** [comment]
> 开启监控消息，起初1-2天内会自动下载，之后就不会，需要重新启动软件才能自动下载上传。

后台也没有报错吗？最近换工作比较忙，没有看这边提的问题

**Comment by 520xcy** [comment]
> > 开启监控消息，起初1-2天内会自动下载，之后就不会，需要重新启动软件才能自动下载上传。
> 
> 后台也没有报错吗？最近换工作比较忙，没有看这边提的问题

辛苦了。我这边后台显示正常，还是在有下载的提示，但是文件不会下载下来。

**Comment by snow922841** [comment]
520xcy <notifications@github.com>于2021年1月22日 周五09:07写道：

**Comment by snow922841** [comment]
可能网络的问题把，如果没有报异常，我这边也不好判断是什么问题。
