### ISSUE TITLE
能否上传到onedrive

### ISSUE THREAD

**Issue by SkfyZ** [snow922841/telegram_channel_downloader#28]
如题，能否上传到OneDrive，或者说可以适配rclone

**Comment by snow922841** [comment]
rclone上传没问题，直接更换fclone为rclone就行，但是要上传OneDrive需要挂载OD，然后在修改上传命令。我感觉比较麻烦。

**Comment by SkfyZ** [comment]
噢噢，好的谢谢，就是直接更换fclone为rclone然后下面的文件位置也改成od对吧？

By トラベラ`

________________________________

**Comment by SkfyZ** [comment]
挂载的话应该不必吧？我记得aria2也是不用挂载的

By トラベラ`

________________________________

**Comment by snow922841** [comment]
那不清楚，你试试把，我很少用OD。

**Comment by SkfyZ** [comment]
嗯，好的，谢谢帮助

By トラベラ`

________________________________

**Comment by SkfyZ** [comment]
您好，我已经改完了但是不知道为什么，卡在了第一个任务，可以正常上传第一张照片，在iftop里没有流量传输。
bot发来信息Soviet Anime all message added to task queue, last message is：10454
然后就没别的了

By トラベラ`

________________________________

**Comment by snow922841** [comment]
能上传下载说明没有问题呀。

**Comment by SkfyZ** [comment]
嗯，我猜测有可能是群组发的图片都是一个名字

By トラベラ`

________________________________

**Comment by snow922841** [comment]
我看你发的群组名称好像是贴纸类的？如果是贴纸，默认不下载的。

**Comment by SkfyZ** [comment]
不是，是文件.jpg和.png

By トラベラ`

________________________________

**Comment by snow922841** [comment]
不好意思才发现之前帮一个印度的小哥改需求，把27行加了一个过滤文件类型的列表，里面有一个JPG，你可以把他删除了。就可以下载jpg文件了。

**Comment by SkfyZ** [comment]
哦哦哦好的

By トラベラ`

________________________________

**Comment by SkfyZ** [comment]
可以了，谢谢

By トラベラ`

________________________________

**Comment by snow922841** [comment]
OK,如果没有什么其他问题麻烦关闭issues

**Comment by SkfyZ** [comment]
重复文件审核时查验md5还是就光看文件名呢？

By トラベラ`

________________________________

**Comment by snow922841** [comment]
不会有重复文件，因为每一条消息都有不同的消息ID，所以不会判断是否重复。

**Comment by SkfyZ** [comment]
好的呢，谢谢，然后最后一个问题就是，下载包括那个文件吧？

By トラベラ`

________________________________

**Comment by SkfyZ** [comment]
不用问了，包括，谢谢了

By トラベラ`

________________________________
