### ISSUE TITLE
优化 文件后缀名 的过滤方式，使程序不会因为'过滤的文件数目'大于'同时下载数目'而停止

### ISSUE THREAD

**Issue by monicedy** [snow922841/telegram_channel_downloader#29]
`
# 修改部分    
def skip(file_name):
    for filter_file in filter_file_name:
            if file_name.endswith(filter_file):
                print('skip .'+filter_file + ' file')
                return True
# 修改部分

async def worker(name):
    while True:
        queue_item = await queue.get()
        message = queue_item[0]
        chat_title = queue_item[1]
        entity = queue_item[2]
        file_name = queue_item[3]
        
        # 修改部分
        if skip(file_name):
            continue
        # 修改部分
        #使其不会因过滤文件太多而停止运行，以下为原代码

        # for filter_file in filter_file_name:
        #     if file_name.endswith(filter_file):
        #         print('find')
        #         return 
`

**Comment by snow922841** [comment]
其实这个功能是给一个印度的小哥加的，如果你需要过滤文件后缀，可以在监听消息的过程中直接过滤，应该程序会快很多。
