### ISSUE TITLE
关于几种ID的困惑咨询

### ISSUE THREAD

**Issue by jcx70100** [snow922841/telegram_channel_downloader#30]
开发者您好，

该程序在配置的时候有几个id需要更改，由于自己在这方面不是很skilled，有几个问题需要请教您，还望指点：
```
api_id    # your telegram api id
api_hash  # your telegram api hash
bot_token # your bot_token
admin_id  # your chat id
```
这里的`api_id`和`api_hash`可以通过您在介绍中给出的[链接](https://my.telegram.org/apps)申请得到；另外两个id我有些困惑。

1. `bot_token`是否意指我需要通过`BotFather`自己创建新的机器人？
2. 如果我之前已经创建过机器人，可否直接将其`bot_token`拿来这里直接使用？**另外，是否需要将该机器人添加到我需要下载文件的群组中？**
3. `admin_id`的注释中解释是`chat id`，不是很清楚其指代的是`需要下载文件的对应群组的id`还是`用户id`？

我进行了以下尝试：
```
api_id    =  已通过链接申请得到
api_hash  =  已通过链接申请得到
bot_token =   先前创建的机器人token，但机器人未添加到对应群组中
admin_id  =  分别填写过“用户id” 和 “群组id”（即web端群组链接中@符号后面的信息）
```
在终端运行后得到以下连接报错：
```
telethon.network.mtprotosender - WARNING - Attempt 1 at connecting failed: TimeoutError: 
```
网络连接确保没有问题，所以想请您看一下我以上的id配置是否有问题？如果存在错误，还请指点一下应该如何配置和获取对应id。

十分感谢

**Comment by snow922841** [comment]
1、bot_token可以用之前你创建的，也可以新建，但是之前创建的必须要没在其他脚本中用。
2、不需要。
3、可以通过在TG中给@get_id_bot这个bot发消息获取自己的用户ID
