### ISSUE TITLE
怎么修改可上传至onedrive

### ISSUE THREAD

**Issue by 503bug** [snow922841/telegram_channel_downloader#31]

**Comment by snow922841** [comment]
rclone挂载od即可。

**Comment by 503bug** [comment]
那么
drive_id  = 
drive_name  =  
呢，怎么修改

**Comment by snow922841** [comment]
好像不怎么适配OD，不好意思。可以选择上传到谷歌盘在上传到OD...

**Comment by snow922841** [comment]
等有空给改一下能上传至OneDrive的版本

**Comment by 503bug** [comment]
感谢

**Comment by snow922841** [comment]
上传OD的方法有了。原脚本不修改的情况下，drive_id=''，drive_name='onedrive'， onedrive 就是你配置rclone的时候填的盘名称， 还有102行的fclone替换为rclone，rclone需要自行安装。

**Comment by 503bug** [comment]
感谢解答
