### ISSUE TITLE
运行成功，但无速度

### ISSUE THREAD

**Issue by edmund-zhao** [snow922841/telegram_channel_downloader#32]
![image](https://user-images.githubusercontent.com/53864204/111322388-d79b4300-86a3-11eb-977e-29b14ca2cf40.png)
成功运行，并且在bot交流页面添加了任务，但是没有任何速度

**Comment by edmund-zhao** [comment]
![image](https://user-images.githubusercontent.com/53864204/111323467-df0f1c00-86a4-11eb-80cb-3850bd934cd2.png)
- 报错如下

**Comment by edmund-zhao** [comment]
`telethon.client.users - WARNING - Telegram is having internal issues TimeoutError:`

**Comment by snow922841** [comment]
建议更换其他地区的VPS

**Comment by edmund-zhao** [comment]
尝试了日本与新加坡都是没有速度。并且没有看到脚本创建的文件夹

发自我的iPhone

在 2021年3月17日，上午12:44，snow922841 ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

建议更换其他地区的VPS

**Comment by snow922841** [comment]
发你的电报号给我，我联系你

ED_Z ***@***.***>于2021年3月17日 周三09:47写道：

**Comment by edmund-zhao** [comment]
@Kancollection
谢谢指导

发自我的iPhone

在 2021年3月17日，上午11:26，snow922841 ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

发你的电报号给我，我联系你

ED_Z ***@***.***>于2021年3月17日 周三09:47写道：

**Comment by peng4740** [comment]
我遇到的问题与你很相似，请问一下你解决这个问题了吗？

**Comment by edmund-zhao** [comment]
并没有解决，怀疑是云服务提供商的问题，请问你是GCP吗

发自我的iPhone

在 2021年3月19日，上午2:51，peng4740 ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

我遇到的问题与你很相似，请问一下你解决这个问题了吗？

**Comment by edmund-zhao** [comment]
> 我遇到的问题与你很相似，请问一下你解决这个问题了吗？

我尝试一下你的解决方案

**Comment by edmund-zhao** [comment]
对的，用这个脚本可以使用https://raw.githubusercontent.com/snow922841/telegram_channel_downloader/84e8df9ac42f1be992e7b85e04959c630c7fccda/tg_channel_downloader.py

**Comment by Sooele** [comment]
我也是这个问题。下载没速度！Vultr测试这玩

**Comment by edmund-zhao** [comment]
用以前的脚本。

发自我的iPhone

在 2021年3月19日，下午5:28，Sooele ***@***.***> 写道：

﻿
EXTERNAL EMAIL:

我也是这个问题。下载没速度！Vultr测试这玩

**Comment by Sooele** [comment]
换Vu新加坡就可以了！
