### ISSUE TITLE
跳过已上传gd的文件

### ISSUE THREAD

**Issue by hc9903** [snow922841/telegram_channel_downloader#34]
希望可以加一个跳过下载 已上传gd的文件 的功能，这样可以避免第二次打开后重复下载，可以对之前的下载进行补全

**Comment by snow922841** [comment]
这个功能不实用，fclone上传的时候会自动去重。也就多下一次而已。

**Comment by hc9903** [comment]
万一是很多条消息，漏了几十条，那么为了这几十条还要重新下载数千条
