### ISSUE TITLE
提交成功，但无法下载，也未显示报错

### ISSUE THREAD

**Issue by nzbcorz** [snow922841/telegram_channel_downloader#36]
如图所示。

![E8A91C60-C835-4F83-B975-B5CC3B09BAB7](https://user-images.githubusercontent.com/25114850/114325546-377df000-9b63-11eb-9a2d-b1da7a5906be.jpeg)

![B7D715F4-485E-4BF4-9AFF-427B8EB2D4E6](https://user-images.githubusercontent.com/25114850/114325549-3e0c6780-9b63-11eb-84bb-1844606e86f8.png)

![C6A582C0-9D4C-4F4C-B57F-CC83B160C30B](https://user-images.githubusercontent.com/25114850/114325553-42388500-9b63-11eb-8f5c-d4ecb4cfd8df.jpeg)

**Comment by liyepan** [comment]
我也是一样的问题，无法解决

**Comment by snow922841** [comment]
有问题的留下频道地址，我测试后给解决方案

**Comment by 2284787774** [comment]
一样的情况，使用https://raw.githubusercontent.com/snow922841/telegram_channel_downloader/84e8df9ac42f1be992e7b85e04959c630c7fccda/tg_channel_downloader.py  这个旧的脚本没问题

**Comment by imi-123** [comment]
> 有问题的留下频道地址，我测试后给解决方案

大佬可以给个联系方式吗，我是个小白，不会编程类的，我只是想下载一些电报频道里的图片。我是在手机上用termux操作的，已经到打开py文件这步了，但是py文件里的一些东西我不知道怎么设置，api id和hash已经弄好了，还有几个我不知道怎么弄，大佬可以教教我吗，希望大佬可以给个联系方式，我的QQ是1786317091

**Comment by comienzo2093** [comment]
我也有同样的问题。

**Comment by comienzo2093** [comment]
> 一样的情况，使用https://raw.githubusercontent.com/snow922841/telegram_channel_downloader/84e8df9ac42f1be992e7b85e04959c630c7fccda/tg_channel_downloader.py 这个旧的脚本没问题

这解决了我的问题。 谢谢。但是我想写最新版本！ 希望这个问题能尽快解决。

**Comment by snow922841** [comment]
已经修复，请尝试更新脚本！ @comienzo2093 @2284787774 @nzbcorz @liyepan

**Comment by zephyr-y** [comment]
> 一样的情况，使用https://raw.githubusercontent.com/snow922841/telegram_channel_downloader/84e8df9ac42f1be992e7b85e04959c630c7fccda/tg_channel_downloader.py 这个旧的脚本没问题  

我也是这样的问题，用这个就的才能下载。 @snow922841
