### ISSUE TITLE
关于上载

### ISSUE THREAD

**Issue by Dingzhenpiyi** [snow922841/telegram_channel_downloader#37]
GDrive团队盘已废，大佬能否把上载改为onedrive business，万分感谢！

**Comment by snow922841** [comment]
> GDrive团队盘已废，大佬能否把上载改为onedrive business，万分感谢！

好的，这两天帮你加上

**Comment by Dingzhenpiyi** [comment]
> > GDrive团队盘已废，大佬能否把上载改为onedrive business，万分感谢！
> 
> 好的，这两天帮你加上

谢谢大佬！

**Comment by snow922841** [comment]
> > > GDrive团队盘已废，大佬能否把上载改为onedrive business，万分感谢！
> > 
> > 
> > 好的，这两天帮你加上
> 
> 谢谢大佬！
已添加OneDrive的配置修改说明。如果有问题请重新打开Issues
