### ISSUE TITLE
同时下载数量设置不生效

### ISSUE THREAD

**Issue by 5536086** [snow922841/telegram_channel_downloader#38]
同时下载数量设置没用，有时候现有任务下载完成之后，就不会添加新任务了

**Comment by snow922841** [comment]
这个脚本用的异步下载，不是多线程、多进程。我也不会写…

**Comment by 5536086** [comment]
> 这个脚本用的异步下载，不是多线程、多进程。我也不会写…

意思是，随着下载时间的推迟，同时下载个数越来越少，最后甚至没有下载个数了

**Comment by snow922841** [comment]
网络问题吧。
