### ISSUE TITLE
出现：SyntaxError: invalid syntax

### ISSUE THREAD

**Issue by Dingzhenpiyi** [snow922841/telegram_channel_downloader#39]
File "tg_channel_downloader.py", line 87
    dirname = validateTitle(f'{chat_title}({entity.id})')

**Comment by snow922841** [comment]
python版本多少？

**Comment by Dingzhenpiyi** [comment]
重新装了ubuntu18.04，python3.6.9，没显示报错，但没有下载，求教大佬！

**Comment by Dingzhenpiyi** [comment]
发送频道消息了呀

**Comment by snow922841** [comment]
已经修复脚本无法下载的问题，请更新后重试！

**Comment by Dingzhenpiyi** [comment]
> 已经修复脚本无法下载的问题，请更新后重试！

跑起来了。感谢大佬！
