### ISSUE TITLE
id

### ISSUE THREAD

**Issue by loeveo** [snow922841/telegram_channel_downloader#4]
作者请问一下，如何修改，让他从ID 0开始下载.顺便还有想请问一下，我之前下载过一次，但是没下载完，然后他的ID是大概在9000多位，然后现在群文件他们又发了东西，有一万多位的文件了，但是他还是会从9000多位往零开始下载，不会充一万位开始下载.下载开始的位置都没变，都是同一个ID

**Comment by snow922841** [comment]
已经更新脚本，现在默认从旧消息开始下载。你直接更新一下就可以了。或者在原来的iter_history()函数中增加一个参数reverse=True

**Comment by loeveo** [comment]
> 你直接更新一下就可以可以了。或者在原来的iter_history（）函数中增加一个参数reverse = True

好的，谢谢大佬，请问一下，我描述的第二个问题，怎么搞？就是文件更新以后，他不会从更新后的下载，还是会从上次开始的那个ID开始.就好像是他没有刷新出来新的消息

**Comment by snow922841** [comment]
现在不会了。之前用redis缓存了消息位置，现在直接从旧往新就避免了这个问题。
