### ISSUE TITLE
上传至google drive 时出现同名文件夹

### ISSUE THREAD

**Issue by zzzqu** [snow922841/telegram_channel_downloader#43]
这些同名文件夹中只有一个包含大部分文件，其余都是只有一两个文件，可能是上传脚本的问题，下载了好几个频道都是这样的问题
![IMG_20210528_113400](https://user-images.githubusercontent.com/77374843/119925753-a050e880-bfa8-11eb-9154-db41b9fc97eb.jpg)

**Comment by snow922841** [comment]
正常情况。下载速度太快了。
