### ISSUE TITLE
求助：各位大佬下载的文件都存到哪了？我想下到本地硬盘里但是一直没成功

### ISSUE THREAD

**Issue by l42172763** [snow922841/telegram_channel_downloader#50]
想问下这个怎么设置能够下载到本地硬盘里？试了很久没能找到cmd中列出的文件被下载到了什么地方。

非常感谢各位大佬

**Comment by l42172763** [comment]
补充，，，，大佬们可以联系我qq：384035963，，，再次感谢

**Comment by resoures** [comment]
> 补充，，，，大佬们可以联系我qq：384035963，，，再次感谢

save_path 参数设置

**Comment by l42172763** [comment]
> > 补充，，，，大佬们可以联系我qq：384035963，，，再次感谢
> 
> save_path 参数设置

save_path = 'N:\TryBotDownloads'  # file save path
这是我目前这一行代码的内容，但是在这个路径下没有找到任何下载的文件，也没有看到有文件正在被下载的迹象，是否有下载成功的全过程截个图，我想可能我丢掉了什么步骤，谢谢您

**Comment by snow922841** [comment]
改成 N:\\TryBotDownloads
