### ISSUE TITLE
文件索引失效了

### ISSUE THREAD

**Issue by resoures** [snow922841/telegram_channel_downloader#53]
针对消息非常多的群，出现The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent的错误

**Comment by snow922841** [comment]
能发个截图吗？> 针对消息非常多的群，出现The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent的错误

**Comment by resoures** [comment]
![image](https://user-images.githubusercontent.com/57185641/128617137-11cda949-5131-42b5-8929-c12fe971988b.png)

**Comment by resoures** [comment]
之前我采用默认的队列长度，下个前几十，就会报文件引用过期了，后来我将队列长度设置为5，勉强可以下载，但一般下载个几十个，然后就会抛出几十个过期的错误，然后继续可以下几十个，循环

**Comment by resoures** [comment]
> 能发个截图吗？> 针对消息非常多的群，出现The file reference has expired and is no longer valid or it belongs to self-destructing media and cannot be resent的错误

已经补充了截图了，
![image](https://user-images.githubusercontent.com/57185641/128617191-6f4f5424-0a93-4d39-90fc-f7472f6c8e4e.png)
![image](https://user-images.githubusercontent.com/57185641/128617198-74ac832f-c5f3-4547-ac02-98df5d3e5bf4.png)
一般消息id在xx31-xxxx(某个值)之间的会下载不了，提示错误

**Comment by snow922841** [comment]
捕获异常名代码写错了。麻烦更新后在下载一个频道多一点的程序，然后把报错截图一下，在修改一次就可以了。

**Comment by resoures** [comment]
> 捕获异常名代码写错了。麻烦更新后在下载一个频道多一点的程序，然后把报错截图一下，在修改一次就可以了。

![image](https://user-images.githubusercontent.com/57185641/128627633-f3b67bb2-0ef3-4934-b3d6-c03ee5ebd87d.png)
错误差不多

**Comment by snow922841** [comment]
感谢。已经修复这个问题。如果有问题麻烦及时反馈。
