### ISSUE TITLE
关于下载消息ID数、下载无错误卡住的请教

### ISSUE THREAD

**Issue by GloryBoy239** [snow922841/telegram_channel_downloader#54]
感谢大佬提供的脚本，这个不是Bug。只是一个请教性问题：

1. 这个消息ID的具体数字对应哪一条“消息文件”，是不是其实是无法不知道的？只是数字越小“消息文件”所在的时间点就越久远

2. 如果首次设定消息ID为0，开始一个群里所有文件下载后，会返回一个：all message added to task queue, last message is：6789。在完成了这次下载后，隔一段时间想要下载群里新的文件，又想避免重复下载时，是不是就把消息ID设定为6789，就实现了“增量下载”？

**Comment by GloryBoy239** [comment]
查看历史消息：https://github.com/snow922841/telegram_channel_downloader/issues/26，发现大佬已经解答：复制消息直链就能看到消息ID。但是这个好像有点问题。
我中午开始下载时，提交下载任务后，大概10来分钟，bot返回：all message added to task queue, last message is：6789。到刚才群里又发了10来个视频文件，我按照这种方式查看刚刚发出来的最后一条消息，直链最末位显示的数字却是 6780。这是怎么回事？

**Comment by snow922841** [comment]
具体我也不太清楚哦，好像频道清理过消息，消息ID会有变化，你可以设置监控这个频道，如果频道有发新消息会自动下载的。

**Comment by GloryBoy239** [comment]
> 具体我也不太清楚，好像频道收集了消息，消息有变化，你可以设置监控这个频道，如果频道有新消息会自动下载的。

好的，谢谢大佬。监控频道是个不错的功能！

现在使用总面临的一个问题：比如发送下载命令后返回有2000多个文件。但是运行中有时多的话能顺畅下载100多200个，少的时候4、50个，就会无错误卡住。脚本最后显示xxxx（比如：1234、1235、1236）几个编号文件在下载中，但是一晚上时间过去却没有进展。探针显示几乎没有什么流量，所以应该就是卡住了。这时停掉脚本重新运行后，从1234开始下载就又能正常了。

**Comment by resoures** [comment]
> 感谢大佬提供的脚本，这个不是Bug。只是一个请教性问题：
> 
> 1. 这个消息ID的具体数字对应哪一条“消息文件”，是不是其实是无法不知道的？只是数字越小“消息文件”所在的时间点就越久远
> 2. 如果首次设定消息ID为0，开始一个群里所有文件下载后，会返回一个：all message added to task queue, last message is：6789。在完成了这次下载后，隔一段时间想要下载群里新的文件，又想避免重复下载时，是不是就把消息ID设定为6789，就实现了“增量下载”？

我记得id是唯一递增的

**Comment by snow922841** [comment]
> > 具体我也不太清楚，好像频道收集了消息，消息有变化，你可以设置监控这个频道，如果频道有新消息会自动下载的。
> 
> 
> 
> 好的，谢谢大佬。监控频道是个不错的功能！
> 
> 
> 
> 现在使用中面临的一个问题：比如发送下载命令后返回有2000多个文件。但是运行中有时多的话能顺畅下载100多200个，少的时候4、50个，就会无错误卡住。脚本最后显示xxxx（比如：234、235、236）几个编号文件在下载中，但是一晚上时间过去却没有进展，tg也没有任何报错信息。探针显示几乎没有什么流量，所以应该就是卡住了。这时停掉脚本重新运行后，从234开始下载就又能正常了。

网络问题大概，我的脚本挂了几个月，几乎没啥问题

**Comment by GloryBoy239** [comment]
好的，谢谢大佬

**Comment by snow922841** [comment]
好像没影响，只是每次重新运行脚本都需要登录，你试试用tmux

**Comment by GloryBoy239** [comment]
感谢大佬
