### ISSUE TITLE
如何过滤后缀？

### ISSUE THREAD

**Issue by GloryBoy239** [snow922841/telegram_channel_downloader#55]
大佬，看了历史帖：[[优化 文件后缀名 的过滤方式，使程序不会因为'过滤的文件数目'大于'同时下载数目'而停止 #29]](https://github.com/snow922841/telegram_channel_downloader/issues/29) ，但是没看明白？

我是想只下载视频，但是群里有很多图片，我想过滤掉。可是在脚本里：filter_file_name = []  # 过滤文件后缀，可以填jpg、avi、mkv、rar等。这一项不知道怎么填？ 总是报错！
另外，你说的：如果你需要过滤文件后缀，可以在监听消息的过程中直接过滤。这个应该怎么操作？

谢谢大佬！

**Comment by snow922841** [comment]
filter_file_name = ['jpg']
像这样就会过滤jpg图片，如果同时过滤png就是
filter_file_name = ['jpg','png']

**Comment by GloryBoy239** [comment]
好的，谢谢大佬
