### ISSUE TITLE
某些频道，下载到特定的消息id时停止下载， 也不报错

### ISSUE THREAD

**Issue by ttlvip** [snow922841/telegram_channel_downloader#60]
Successfully started (Press Ctrl+C to stop)
2021-09-12 19:00:07 - 开始下载：美图秀秀(1234008035) - 12450
2021-09-12 19:00:07 开始下载： 美图秀秀 - 12451 - 5005978344667328312.jpg
2021-09-12 19:00:07 开始下载： 美图秀秀 - 12452 - 5005978344667328313.jpg
=======================================================
上面的日志是我从 美图秀秀(1234008035)  频道下载12450开始下载， 到12453时就不动了。 我试了从12453以后的消息id开始下载，仍然是无法下载， 只有12453之前的可以正常下载。 不知道是什么原因

**Comment by ttlvip** [comment]
停止下载一段时间后， telegram机器人上面提示：
![image](https://user-images.githubusercontent.com/32515374/132985166-941eb9d4-e429-42f5-965f-352b74f54f2d.png)

**Comment by ttlvip** [comment]
经过在频道中按照消息id查找， 确认从12453一直到23868 都是视频， 而我过滤掉了视频消息的下载。可能是连续跳过太多导致的问题。

**Comment by snow922841** [comment]
拉取消息也是有限制的，消息太多会被telegram服务器强制停止一段时间

**Comment by ttlvip** [comment]
> 拉取消息也是有限制的，消息太多会被telegram服务器强制停止一段时间

感谢解答. 我直接从23868 开始, 可以正常下载到结束了40082.
