### ISSUE TITLE
有没有教程

### ISSUE THREAD

**Issue by zutuvip** [snow922841/telegram_channel_downloader#63]
大佬 可不可以写一个教程啊 挂在网站上 我可以提供小鸡服务器🤣🤣   总是出错 找不到问题出在哪里

**Comment by jjzwwww** [comment]
https://cnboy.org/archives/2163
另一个大佬的教程。希望可以帮到你。

**Comment by zutuvip** [comment]
大佬 我看了他那个文章 🤣🤣可以加你个联系方式嘛  什么都搞好了 就是最后一步运行脚本输入手机号死活不成功

**Comment by designfuchen** [comment]
![image](https://user-images.githubusercontent.com/17679892/147376689-1500fa6f-2918-4ef3-837f-7441394a5a31.jpeg)最后一步发给机器人后也没反馈，终端也没下载，请求大神帮助

**Comment by snow922841** [comment]
> ![image](https://user-images.githubusercontent.com/17679892/147376689-1500fa6f-2918-4ef3-837f-7441394a5a31.jpeg)最后一步发给机器人后也没反馈，终端也没下载，请求大神帮助

你使用的是机器人账号登陆的，删除文件夹内的.session 文件后用你手机号登陆
