### ISSUE TITLE
当有新的文件时不会自动下载；

### ISSUE THREAD

**Issue by nomoneynolife** [snow922841/telegram_channel_downloader#65]
例如；
在12点运行python3 tg_channel_downloader.py
只会下载群组中12点之前的文件，

12点之后的文件不会自动下载；

命令行会停留在最后下载的文件处，有监听新文件的功能吗~

感谢大佬的项目！666666

配置就是默认配置；

WINDOWS 10 PYTHON 3.9.6

**Comment by snow922841** [comment]
脚本内修改26行的false为True
