### ISSUE TITLE
TypeError: 'AsyncGenerator' object is not iterable

### ISSUE THREAD

**Issue by ChanucyHe** [snow922841/telegram_channel_downloader#8]
运行时候报错，tg_channel_downloader.py:139: RuntimeWarning: coroutine 'Client.start' was never awaited
  app.start()
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
Traceback (most recent call last):
  File "tg_channel_downloader.py", line 140, in <module>
    main()
  File "tg_channel_downloader.py", line 51, in main
    for message in app.iter_history(chat_id=chat_id, offset_id=offset_id, reverse=reverse):
TypeError: 'AsyncGenerator' object is not iterable
开始是报 api_id/api_hash combination is invalid，网上搜了下，后来不知道怎么弄的报这个错了

**Comment by snow922841** [comment]
已经对脚本进行重构。欢迎测试，有问题可以直接提issue
